[tools]

# JVM
java = "zulu-21"
kotlin = { version = "2.4.0", bin_path = "kotlinc/bin", asset_pattern = "kotlin-compiler-*.zip" }
gradle = "9.5.1"

# JS
node = "26.3.0"
bun = "1.3.14"

# Python
python = "3.14.6"
uv = "0.11.19"

[settings]
minimum_release_age = "7d"
idiomatic_version_file_enable_tools = ["java", "node", "python"]

[settings.java]
shorthand_vendor = "zulu"

[settings.node]
corepack = true
