[tools]

# JVM
java = "zulu-21"
kotlin = { version = "2.4.10", bin_path = "kotlinc/bin", asset_pattern = "kotlin-compiler-*.zip" }
gradle = "9.7.1"

# JS
node = "26.7.0"
bun = "1.4.0"

# Python
python = "3.14.7"
uv = "0.12.5"

# Go
go = "1.27"

[settings]
minimum_release_age = "3d"
idiomatic_version_file_enable_tools = ["java", "node", "python"]

[settings.java]
shorthand_vendor = "zulu"

[settings.node]
corepack = true
